on: [push]

jobs:
  ubuntu16:
    runs-on: ubuntu-latest
    name: Test on Ubuntu 16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile and test
      uses: ./.github/actions/ubuntu16
  ubuntu18:
    runs-on: ubuntu-latest
    name: Test on Ubuntu 18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile and test
      uses: ./.github/actions/ubuntu18
  ubuntu20:
    runs-on: ubuntu-latest
    name: Test on Ubuntu 20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile and test
      uses: ./.github/actions/ubuntu20
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |
          graphicscache.tar.gz
          graphicscache.pdf
          graphicscache.sty
  windows_miktex:
    runs-on: windows-latest
    name: Test on Windows using MikTeX
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile and test
      uses: ./.github/actions/windows
  windows_texlive:
    runs-on: windows-latest
    name: Test on Windows using TeX Live
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile and test
      uses: ./.github/actions/windows_texlive

 
